### ISSUE TITLE
Error working inside a modal

### ISSUE THREAD

**Issue by Quacrom** [mikejacobson/bootstrap4-scrolling-tabs#3]
When I try to execute the pluging within a modal, the following happens:

The width of the DIV `scrtabs-tabs-fixed-container` and `scrtabs-tabs-movable-container` have the same value (I presume an element recognition error). In this case both values are calculated with 1108px:

![imagen](https://user-images.githubusercontent.com/13321249/120142517-6e0fd880-c1ac-11eb-8ea8-a5683d2e4ed1.png)

This causes the width to show it the same as the total width, so the pluging can not work correctly:

![imagen](https://user-images.githubusercontent.com/13321249/120142649-9d264a00-c1ac-11eb-9ff8-b9ec410d23e8.png)

More displacement:

![imagen](https://user-images.githubusercontent.com/13321249/120142669-a4e5ee80-c1ac-11eb-85b4-335fe89881bc.png)

Any solution to this?

Thanks again!

**Comment by mikejacobson** [comment]
If you're using a Bootstrap modal, try calling the plugin's `refresh` method when the modal's `shown.bs.modal` event fires:
```js
$('#divModal').on('shown.bs.modal', function () {
  $('.nav-tabs').scrollingTabs('refresh'); // <-- refresh plugin here
});

$('.nav-tabs').scrollingTabs();
```
This came up before with the Bootstrap 3 plugin. [Here's a pen](https://codepen.io/mikejacobson/pen/ywMBJO?editors=0010) showing it working with that plugin, but it should work here, also.

**Comment by Quacrom** [comment]
Thanks for the answer Mike!

Indeed the "Refresh" option is the solution to accommodate correctly, but in the manner indicated I can not shoot it.

The problem is that in this case, the modal is generated dynamically, so that the content of the modal "does not exist" at first and before generating calls.

The code I use to generate the modal and try to call the refresh option in this way:

```
$("body").on('click', "[id*='get_modal_contact']", function() 
{
	requestGet('url/').done(function(response) {
		$('#contact_data').html(response);
		$('#contact_modal').modal({
			show: true,
			backdrop: 'static'
		});

		$('body').off('shown.bs.modal', '#contact_modal');
		$('body').on('shown.bs.modal', '#contact_modal', function() {
			$('#contact_modal').find('input[name="field_name"]').focus();
			// $('.nav-tabs').scrollingTabs('refresh');
			$('#contact_modal').find('.nav-tabs').scrollingTabs('refresh');
		});

		init_tabs_scrollable();	//	scrollingTabs call
	});
});
```

But it does not turn out. If I press a button inside the modal with the code with reference to the Refresh option (`<span onclick="$('.nav-tabs').scrollingTabs('refresh');">refresh tabs</span>`) works well and the Tab menu is correctly accommodated correctly, but automatically (as it should be) I can not do it.

![imagen](https://user-images.githubusercontent.com/13321249/120243899-bd9ae680-c236-11eb-8e7c-f7ba384cfd7e.png)

..........

![imagen](https://user-images.githubusercontent.com/13321249/120243916-c7bce500-c236-11eb-89ec-41b03cefc8df.png)

Can you give me a hand?

**Comment by mikejacobson** [comment]
Try moving the `init_tabs_scrollable()` call so it's inside the `$('body').on('shown.bs.modal'...` event handler function (assuming `init_tabs_scrollable()` is the initial call to `.scrollingTabs({...})`).

You might even need to wrap that call inside a `setTimeout` to give the tabs time to render before having the plugin act on them. But the tabs do need to be present in the DOM for the plugin to configure the scrolling correctly.

If you make that change, you probably won't even need a `refresh` call since you won't be initializing the plugin until the tabs are already settled into their final size and position in the modal, so an additional refresh on top of the initialization shouldn't be necessary.

**Comment by Quacrom** [comment]
Mike.

According to your recommendation left the code like this:

```
......
$('body').on('shown.bs.modal', '#contact_modal', function() {
	....
	setTimeout(function(){ 
		init_tabs_scrollable();
	}, 500);
});
......
```

Remove the Refresh option (as you said) and it works very well.

Thank you very much for your help!.

**Comment by mikejacobson** [comment]
Excellent! Glad to hear it's working. 👍
